spring:
  application:
    name: demo-mcp-server
  ai:
    mcp:
      server:
        protocol: stateless
        name: demo-mcp-server

server:
  port: ${PORT:8080}
  servlet:
    session:
      persistent: true

logging:
  level:
    com.mla.mcp: DEBUG
    org.springframework.security: TRACE
